<a href="https://colab.research.google.com/github/Justin-Nguyen-312/thuchanhdeeplearning/blob/main/H%E1%BB%8Dc_Deep_online.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#array 1 chieu

import numpy as np

my_list = [1, 9, 15, 39]
print('Python list: ', my_list)

my_numpy_array = np.array(my_list)
print('Numpy array: ', my_numpy_array)

a = np.array([1, 9, 15, 39])
print(a)



Python list:  [1, 9, 15, 39]
Numpy array:  [ 1  9 15 39]
[ 1  9 15 39]


In [ ]:
#array 2 chieu

import numpy as np

c = np.array([(1, 2, 3),
              (4, 5, 6)
              ])

print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [ ]:
#array 3 chieu

import numpy as np

d = np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[7., 8., 9.], [10, 11,12]]
    ])
print(d)
print(d.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)


In [ ]:
#tao array 0 1

import numpy as np

e = np.zeros((2, 2))
f = np.ones((3, 3))
print('Zero matrix: \n', e)
print('One matrix: \n', f)

Zero matrix: 
 [[0. 0.]
 [0. 0.]]
One matrix: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [1]:
# thay đổi kích thước ma trận

import numpy as np

e = np.array([[1., 2., 3.], [4., 5., 6.]])
print(e)
print(e.shape)
f = e.reshape(3,2)
print(f)
g = np.array([[[1., 2., 3.], [4., 5., 6.]],
              [[7., 8., 9.], [10., 11., 12.]]
              ])
print(g)
print(g.shape)
h = g.reshape(3, 4)
print('reshape (3, 4) \n', h)
j = g.reshape(3, 2, 2)
print('reshape (3, 2, 2) \n', j)
k = g.reshape(2, 3, 2)
print('reshape (2, 3, 2) \n', k)


[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
reshape (3, 4) 
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
reshape (3, 2, 2) 
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
reshape (2, 3, 2) 
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]


In [2]:
# flatten

import numpy as np

e = np.array([[1., 2., 3.], [4., 5., 6.]])
f= e.flatten()
print(f)
g = np.array([[[1., 2., 3.], [4., 5., 6.]],
             [[7., 8., 9.], [10., 11., 12.]]
             ])
j = g.flatten()
print(j)

[1. 2. 3. 4. 5. 6.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


In [3]:
# them dong du lieu voi hstack va vstack

import numpy as np

f = np.array([1., 2., 3.])
g = np.array([4., 5., 6.])
h_stack = np.hstack((f, g))
print('Horizontal Append\n', h_stack)
v_stack = np.vstack((f, g))
print('Vertical Append\n', v_stack)

Horizontal Append
 [1. 2. 3. 4. 5. 6.]
Vertical Append
 [[1. 2. 3.]
 [4. 5. 6.]]


In [4]:
# sinh mang so nguyen ngau nhien

import numpy as np

a = np.random.randint(100, size=(5,))
print('Random 1-D array\n', a)
b = np.random.randint(100, size=(3, 4))
print('Random 2-D array\n', b)
c = np.random.randint(100, size=(3, 4, 3))
print('Random 3-D array\n', c)


Random 1-D array
 [88 93 70 27 23]
Random 2-D array
 [[68 63 43 57]
 [42 43 96 21]
 [ 6 53 72  1]]
Random 3-D array
 [[[84 62 22]
  [87 50 77]
  [ 7 82 14]
  [76 47  1]]

 [[15 60 51]
  [98  7 36]
  [32 80 12]
  [55 55 57]]

 [[25  6 64]
  [56 56 80]
  [96 42 43]
  [81 98 66]]]


In [7]:
# sinh ngay nhien so thuc [0, 1]

import numpy as np

a = np.random.rand(5)
print('Random 1-D array\n', a)
b = np.random.rand(3, 4)
print('Randon 2-d array\n', b)
c = np.random.rand(3, 4, 3)
print('Random 3-D array\n', c)

a = np.random.normal(5, 0.5, 10)
print(a)

Random 1-D array
 [0.44372447 0.4116175  0.11431538 0.35142842 0.66460979]
Randon 2-d array
 [[0.42849574 0.8728397  0.76101391 0.22703367]
 [0.91711178 0.38910432 0.14315904 0.31588256]
 [0.48661714 0.18512198 0.45975409 0.58399596]]
Random 3-D array
 [[[8.60362387e-01 9.17042239e-01 9.94651223e-01]
  [3.12097279e-01 9.55079659e-01 2.24784424e-01]
  [1.87663811e-02 9.08083919e-01 5.99936978e-05]
  [3.34076264e-01 4.02724929e-01 7.00447267e-01]]

 [[5.35672975e-01 8.43483689e-01 4.69615696e-01]
  [8.52427801e-01 7.85240104e-01 5.64814625e-01]
  [3.52724482e-01 3.53926557e-01 2.18817366e-01]
  [2.85782541e-01 6.52398373e-01 9.29459781e-01]]

 [[8.47233974e-01 4.90361054e-02 3.35660399e-01]
  [3.69195624e-01 6.53382824e-01 5.60582512e-02]
  [5.45541327e-01 9.03261139e-01 1.20163258e-01]
  [1.72337630e-01 2.69058869e-01 8.68201138e-01]]]
[4.65115465 5.81068945 5.39981526 5.43123881 5.64812656 4.62789834
 5.24985964 5.49383464 5.71035047 5.12388287]


In [8]:
# sinh ngau nhien 1 gia tri tu mang gia tri cho truoc

import numpy as np

a = np.random.choice([2, 4, 6, 88, 10, 12, 14, 16, 18, 20])
print(a)

b = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20], size=(3, 5))
print(b)

12
[[12  8  6  4  2]
 [10  8  2 14  8]
 [ 6  6  2 14 10]]


In [ ]:
# thay doi gia tri ma tran

import numpy as np
