<a href="https://colab.research.google.com/github/Justin-Nguyen-312/thuchanhdeeplearning/blob/main/H%E1%BB%8Dc_Deep_online.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
#array 1 chieu

import numpy as np

my_list = [1, 9, 15, 39]
print('Python list: ', my_list)

my_numpy_array = np.array(my_list)
print('Numpy array: ', my_numpy_array)

a = np.array([1, 9, 15, 39])
print(a)



Python list:  [1, 9, 15, 39]
Numpy array:  [ 1  9 15 39]
[ 1  9 15 39]


In [6]:
#array 2 chieu

import numpy as np

c = np.array([(1, 2, 3),
              (4, 5, 6)
              ])

print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [7]:
#array 3 chieu

import numpy as np

d = np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[7., 8., 9.], [10, 11,12]]
    ])
print(d)
print(d.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)


In [8]:
#tao array 0 1

import numpy as np

e = np.zeros((2, 2))
f = np.ones((3, 3))
print('Zero matrix: \n', e)
print('One matrix: \n', f)

Zero matrix: 
 [[0. 0.]
 [0. 0.]]
One matrix: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
