<a href="https://colab.research.google.com/github/Justin-Nguyen-312/thuchanhdeeplearning/blob/main/H%E1%BB%8Dc_Deep_online.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

numpy

In [ ]:
#array 1 chieu

import numpy as np

my_list = [1, 9, 15, 39]
print('Python list: ', my_list)

my_numpy_array = np.array(my_list)
print('Numpy array: ', my_numpy_array)

a = np.array([1, 9, 15, 39])
print(a)



Python list:  [1, 9, 15, 39]
Numpy array:  [ 1  9 15 39]
[ 1  9 15 39]


In [ ]:
#array 2 chieu

import numpy as np

c = np.array([(1, 2, 3),
              (4, 5, 6)
              ])

print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [ ]:
#array 3 chieu

import numpy as np

d = np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[7., 8., 9.], [10, 11,12]]
    ])
print(d)
print(d.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)


In [ ]:
#tao array 0 1

import numpy as np

e = np.zeros((2, 2))
f = np.ones((3, 3))
print('Zero matrix: \n', e)
print('One matrix: \n', f)

Zero matrix: 
 [[0. 0.]
 [0. 0.]]
One matrix: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [1]:
# thay đổi kích thước ma trận

import numpy as np

e = np.array([[1., 2., 3.], [4., 5., 6.]])
print(e)
print(e.shape)
f = e.reshape(3,2)
print(f)
g = np.array([[[1., 2., 3.], [4., 5., 6.]],
              [[7., 8., 9.], [10., 11., 12.]]
              ])
print(g)
print(g.shape)
h = g.reshape(3, 4)
print('reshape (3, 4) \n', h)
j = g.reshape(3, 2, 2)
print('reshape (3, 2, 2) \n', j)
k = g.reshape(2, 3, 2)
print('reshape (2, 3, 2) \n', k)


[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
reshape (3, 4) 
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
reshape (3, 2, 2) 
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
reshape (2, 3, 2) 
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]


In [2]:
# flatten

import numpy as np

e = np.array([[1., 2., 3.], [4., 5., 6.]])
f= e.flatten()
print(f)
g = np.array([[[1., 2., 3.], [4., 5., 6.]],
             [[7., 8., 9.], [10., 11., 12.]]
             ])
j = g.flatten()
print(j)

[1. 2. 3. 4. 5. 6.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


In [3]:
# them dong du lieu voi hstack va vstack

import numpy as np

f = np.array([1., 2., 3.])
g = np.array([4., 5., 6.])
h_stack = np.hstack((f, g))
print('Horizontal Append\n', h_stack)
v_stack = np.vstack((f, g))
print('Vertical Append\n', v_stack)

Horizontal Append
 [1. 2. 3. 4. 5. 6.]
Vertical Append
 [[1. 2. 3.]
 [4. 5. 6.]]


In [4]:
# sinh mang so nguyen ngau nhien

import numpy as np

a = np.random.randint(100, size=(5,))
print('Random 1-D array\n', a)
b = np.random.randint(100, size=(3, 4))
print('Random 2-D array\n', b)
c = np.random.randint(100, size=(3, 4, 3))
print('Random 3-D array\n', c)


Random 1-D array
 [88 93 70 27 23]
Random 2-D array
 [[68 63 43 57]
 [42 43 96 21]
 [ 6 53 72  1]]
Random 3-D array
 [[[84 62 22]
  [87 50 77]
  [ 7 82 14]
  [76 47  1]]

 [[15 60 51]
  [98  7 36]
  [32 80 12]
  [55 55 57]]

 [[25  6 64]
  [56 56 80]
  [96 42 43]
  [81 98 66]]]


In [7]:
# sinh ngay nhien so thuc [0, 1]

import numpy as np

a = np.random.rand(5)
print('Random 1-D array\n', a)
b = np.random.rand(3, 4)
print('Randon 2-d array\n', b)
c = np.random.rand(3, 4, 3)
print('Random 3-D array\n', c)

a = np.random.normal(5, 0.5, 10)
print(a)

Random 1-D array
 [0.44372447 0.4116175  0.11431538 0.35142842 0.66460979]
Randon 2-d array
 [[0.42849574 0.8728397  0.76101391 0.22703367]
 [0.91711178 0.38910432 0.14315904 0.31588256]
 [0.48661714 0.18512198 0.45975409 0.58399596]]
Random 3-D array
 [[[8.60362387e-01 9.17042239e-01 9.94651223e-01]
  [3.12097279e-01 9.55079659e-01 2.24784424e-01]
  [1.87663811e-02 9.08083919e-01 5.99936978e-05]
  [3.34076264e-01 4.02724929e-01 7.00447267e-01]]

 [[5.35672975e-01 8.43483689e-01 4.69615696e-01]
  [8.52427801e-01 7.85240104e-01 5.64814625e-01]
  [3.52724482e-01 3.53926557e-01 2.18817366e-01]
  [2.85782541e-01 6.52398373e-01 9.29459781e-01]]

 [[8.47233974e-01 4.90361054e-02 3.35660399e-01]
  [3.69195624e-01 6.53382824e-01 5.60582512e-02]
  [5.45541327e-01 9.03261139e-01 1.20163258e-01]
  [1.72337630e-01 2.69058869e-01 8.68201138e-01]]]
[4.65115465 5.81068945 5.39981526 5.43123881 5.64812656 4.62789834
 5.24985964 5.49383464 5.71035047 5.12388287]


In [8]:
# sinh ngau nhien 1 gia tri tu mang gia tri cho truoc

import numpy as np

a = np.random.choice([2, 4, 6, 88, 10, 12, 14, 16, 18, 20])
print(a)

b = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20], size=(3, 5))
print(b)

12
[[12  8  6  4  2]
 [10  8  2 14  8]
 [ 6  6  2 14 10]]


In [9]:
import numpy as np

A = np.matrix(np.ones((5, 5)))
print('The matrix\n', A)

np.array(A)[2] = 2
print('Change values of third row with array\n', A)

np.asarray(A)[2] = 2
print('Change values of third row with asarray\n', A)


The matrix
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with array
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with asarray
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [11]:
#tạo 20 số nguyên từ 1 --> (n-1)
a = np.arange(1, 20)
print(a)

#tạo 20 số nguyên từ 1 --> (n-1), mỗi bước tăng 2 giá trị
b = np.arange(1, 20, 2)
print(b)

a = np.linspace(1., 5., num=10)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [12]:
#slice
a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)
print('first row:', a[0])
print('second row:', a[1])

#indexing
print('Second column:', a[:, 1])
print('first column:', a[:, 0])
print('First two values of second row:', a[1, :2])

[[1 2 3]
 [4 5 6]]
first row: [1 2 3]
second row: [4 5 6]
Second column: [2 5]
first column: [1 4]
First two values of second row: [4 5]


Pandas

In [15]:
#Tạo pandas series từ list
import pandas as pd

a = pd.Series([1., 2., 3.])
print(a)
print('First value:', a[0])

b = pd.Series([1., 2., 3.], index=['a', 'b', 'c'])
print(b)
print('First value:', b['a'])

#Tạo pandas series từ dictionary
calories = {"day1": 420, "day2": 380, "day3": 390}
myvar = pd.Series(calories)
print(myvar)

#Numpy --> Pandas
h = np.array([[1, 2], [3, 4]])
df_h = pd.DataFrame(h)
print('DataFrame:\n', df_h)

#Pandas --> Numpy
numpy_h = np.array(df_h)
print('Numpy array:\n', numpy_h)

0    1.0
1    2.0
2    3.0
dtype: float64
First value: 1.0
a    1.0
b    2.0
c    3.0
dtype: float64
First value: 1.0
day1    420
day2    380
day3    390
dtype: int64
DataFrame:
    0  1
0  1  2
1  3  4
Numpy array:
 [[1 2]
 [3 4]]


In [17]:
dic = {'Name':['John', 'Smith'], 'Age':[30, 40]}
df_dic = pd.DataFrame(dic)
print(df_dic)

#tạo mảng 20 x 4
r = np.random.randn(20, 4)
df = pd.DataFrame(r, columns=['so1', 'so2', 'so3', 'so4'])
print(df.head())  #in 5 dòng đầu tiên

    Name  Age
0   John   30
1  Smith   40
        so1       so2       so3       so4
0  0.032612 -1.116474 -0.211219 -0.275012
1 -0.295771 -1.309399  1.709687 -0.788705
2  0.436273 -0.271641  1.310760  0.170679
3 -0.616907 -0.403032  1.189013 -0.584084
4  0.844109  1.645863  0.798835 -0.431786


In [19]:
#tạo mảng 20 x 4
r = np.random.randn(20, 4)
df = pd.DataFrame(r, columns=['so1', 'so2', 'so3', 'so4'])
print(df.head())  #in 5 dòng đầu tiên

#chọn 1 cột
print('Chọn cột so1\n', df['so1'])

#chọn nhiều dòng
print('Chọn nhiều dòng\n', df[0:3])

#chọn nhiều cột
print('Chọn nhiều cột\n', df[['so1', 'so3']])

#chọn nhiều dòng, nhiều cột
print('Chọn nhiều dòng, nhiều cột\n', df.iloc[:3, :2])

#Xóa cột
df = df.drop(columns=['so1', 'so4'])
print(df)

        so1       so2       so3       so4
0  1.269303 -0.992503 -0.491098  0.548259
1 -1.022253  0.230767  2.064770  0.172922
2 -0.137141 -0.947815 -0.772953  0.278658
3  1.170308  1.215153  0.242105 -3.145751
4 -1.298933 -0.535187 -0.029481  0.446288
Chọn cột so1
 0     1.269303
1    -1.022253
2    -0.137141
3     1.170308
4    -1.298933
5     0.072719
6    -0.032677
7     1.665313
8     0.273666
9     0.197592
10    1.020542
11   -0.946669
12   -0.658554
13    2.277659
14    0.305532
15    0.309733
16   -0.740195
17   -0.208483
18   -1.865746
19   -1.359950
Name: so1, dtype: float64
Chọn nhiều dòng
         so1       so2       so3       so4
0  1.269303 -0.992503 -0.491098  0.548259
1 -1.022253  0.230767  2.064770  0.172922
2 -0.137141 -0.947815 -0.772953  0.278658
Chọn nhiều cột
          so1       so3
0   1.269303 -0.491098
1  -1.022253  2.064770
2  -0.137141 -0.772953
3   1.170308  0.242105
4  -1.298933 -0.029481
5   0.072719 -1.587178
6  -0.032677 -0.451113
7   1.665313 -0.534586


In [20]:
#Nối 2 DataFrame
df1 = pd.DataFrame({'Name':['John', 'Smith', 'Paul'],
                    'Age':[25, 30, 50]
                    }, index=[0, 1, 2])
df2 = pd.DataFrame({'Name':['Adam', 'Smith'],
                    'Age':[26, 11]
                    }, index=[3, 4])

df_concat = pd.concat([df1, df2])
print('Concate two DataFrame\n', df_concat)

#Xóa những giá trị ở cột Name trùng nhau
print('Drop duplicatevalues in DataFrame\n', df_concat.drop_duplicates('Name'))

#Sắp xếp theo cột
print('Sort values in DataFrame\n', df_concat.sort_values('Age'))

#Đổi tên cột
df_rename = df_concat.rename(columns={'Name': 'Surname', 'Age': 'Age_pupil'})
print('Rename columns of DataFrame\n', df_rename)

        so1       so2       so3       so4
0 -0.170347 -0.994055 -1.682726  0.883808
1 -0.417518  0.322323  1.454093  1.285719
2 -0.412525  0.179231 -0.231080  1.456353
3 -0.434923  0.321676 -0.499649 -1.523126
4  0.398088 -1.534183  0.271177 -1.099683
Chọn cột so1
 0    -0.170347
1    -0.417518
2    -0.412525
3    -0.434923
4     0.398088
5    -0.121443
6    -0.352082
7     0.915189
8     1.949624
9    -2.454428
10   -0.504817
11    0.029610
12    0.998844
13    1.150520
14    1.337845
15    1.045068
16   -0.046807
17    0.327643
18    0.535286
19   -1.228831
Name: so1, dtype: float64
Chọn nhiều dòng
         so1       so2       so3       so4
0 -0.170347 -0.994055 -1.682726  0.883808
1 -0.417518  0.322323  1.454093  1.285719
2 -0.412525  0.179231 -0.231080  1.456353
Chọn nhiều cột
          so1       so3
0  -0.170347 -1.682726
1  -0.417518  1.454093
2  -0.412525 -0.231080
3  -0.434923 -0.499649
4   0.398088  0.271177
5  -0.121443  1.770055
6  -0.352082  0.685229
7   0.915189 -0.604398
